### ISSUE TITLE
Pra que serve a diretiva envDev?

### ISSUE THREAD

**Issue by girol** [uspdev/ccg#107]
Link da linha abaixo:

https://github.com/uspdev/ccg/blob/5aeec5086742b571a06a9a37392fdd4a8a6372d6/config/ccg.php#L55

Pq não usar o `APP_ENV` ?

**Comment by alecostaweb** [comment]
Na verdade basta deixar o CODPES_ALUNO, se for preenchido é desenvolvimento se não é produção.

**Comment by girol** [comment]
Eu não sei se essa é uma boa abordagem visto que não é óbvio pra quem ler, fora outras checagens que podem passar e arriscar quebrar o sistema em produção. O ideal seriam duas checagens (sugestão apenas):

1) Ver o `APP_ENV` e checar se é `production` ou `local` (padrão do Laravel)
2) Se é `local` e o `CODPES_ALUNO` estiver vazio, dá um `die()` e instrui o desenvolvedor a preencher o `.env` com o número USP do aluno de testes.

**Comment by girol** [comment]
Fechado em #108
