### ISSUE TITLE
Em Meus créditos, acrescentar a aba "Relatório", será a versão impressa em PDF a ser assinada e entregue ao Aluno

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/ccg#93]

**Comment by thiagogomesverissimo** [comment]
podemos usar a biblioteca que o @masaki publicou aqui para geração de pdfs.

**Comment by alecostaweb** [comment]
:ok

**Comment by alecostaweb** [comment]
incluir caixa de texto para comentários do Serviço de Graduação

**Comment by alecostaweb** [comment]
> podemos usar a biblioteca que o @masaki publicou aqui para geração de pdfs.

Pensei em usar isso:
https://github.com/barryvdh/laravel-snappy
